build:
  image: dolanor/golang:nosslverify

  commands:
    - go get -v
    - go build
    - mkdir dist
    - mv ovpnsplit dist/ovpnsplit.x64
    - GOARCH=386 go build
    - mv ovpnsplit dist/ovpnsplit.386

publish:
  github_release:
    api_key: $$GITHUB_API_KEY
    files:
      - dist/*

deploy:
  git_push:
    remote: git@github.com:dolanor/ovpnsplit.git
    force: false
